7.线程的属性

![image-20201207190206900](C:\Users\localuser\AppData\Roaming\Typora\typora-user-images\image-20201207190206900.png)

![image-20201207190248411](C:\Users\localuser\AppData\Roaming\Typora\typora-user-images\image-20201207190248411.png)

![image-20201207192657122](C:\Users\localuser\AppData\Roaming\Typora\typora-user-images\image-20201207192657122.png)

![image-20201207192840786](C:\Users\localuser\AppData\Roaming\Typora\typora-user-images\image-20201207192840786.png)

![image-20201207193144194](C:\Users\localuser\AppData\Roaming\Typora\typora-user-images\image-20201207193144194.png)



![image-20201207193801762](C:\Users\localuser\AppData\Roaming\Typora\typora-user-images\image-20201207193801762.png)

```java
/**
 * 描述： 单线程 抛出处理，有异常堆栈
 *      多线程， 子线程发生异常，会有什么不同？
 *
 */
public class ExceptionInChildThread implements Runnable {

    public static void main(String[] args) {
        new Thread(new ExceptionInChildThread()).start();
        for (int i = 0; i < 1000; i++) {
            System.out.println(i);  // 主线程会继续执行
        }
    }

    @Override
    public void run() {
        throw new RuntimeException();  //子线程 抛出异常
    }
}
```

![image-20201207194421571](C:\Users\localuser\AppData\Roaming\Typora\typora-user-images\image-20201207194421571.png)

```java
/**
 * 说明传统异常不能被传统方法捕获:
 * 1. 不加 try/catch ,抛出 4个异常，都带线程名字
 * 2. 使用try / catch 捕获异常，但是无法进行捕获，当前 try / catch 是在主线程进行的，无法捕获 子线程的 异常
 */
public class CantCatchDirectly implements Runnable {

    public static void main(String[] args) throws InterruptedException {
        // 2. 使用try / catch 捕获异常，但是无法进行捕获，当前 try / catch 是在主线程进行的，无法捕获 子线程的 异常
        try {

            new Thread(new CantCatchDirectly(), "Mythread-1").start();
            Thread.sleep(300);
            new Thread(new CantCatchDirectly(), "Mythread-2").start();
            Thread.sleep(300);
            new Thread(new CantCatchDirectly(), "Mythread-3").start();
            Thread.sleep(300);
            new Thread(new CantCatchDirectly(), "Mythread-4").start();
        }catch (RuntimeException e){
            System.out.println("Catch Exception");
        }
        // 1. 没有使用try catch 进行捕获
//        new Thread(new CantCatchDirectly(), "Mythread-1").start();
//        Thread.sleep(300);
//        new Thread(new CantCatchDirectly(), "Mythread-2").start();
//        Thread.sleep(300);
//        new Thread(new CantCatchDirectly(), "Mythread-3").start();
//        Thread.sleep(300);
//        new Thread(new CantCatchDirectly(), "Mythread-4").start();
    }


    @Override
    public void run() {
        throw new RuntimeException();
    }

}
```



![image-20201207195702222](C:\Users\localuser\AppData\Roaming\Typora\typora-user-images\image-20201207195702222.png)

解决方法：

![image-20201207195851706](C:\Users\localuser\AppData\Roaming\Typora\typora-user-images\image-20201207195851706.png)

方案1：

```java
/**
 * 
 */
public class CantCatchDirectly implements Runnable {

    public static void main(String[] args) throws InterruptedException {
        
        new Thread(new CantCatchDirectly(), "Mythread-1").start();
        Thread.sleep(300);
        new Thread(new CantCatchDirectly(), "Mythread-2").start();
        Thread.sleep(300);
        new Thread(new CantCatchDirectly(), "Mythread-3").start();
        Thread.sleep(300);
        new Thread(new CantCatchDirectly(), "Mythread-4").start();

    }
    
    @Override
    public void run() {
        try {
            throw new RuntimeException();
        }catch (RuntimeException e){
            System.out.println("Catch Exception");
        }
    }
}
```



方案二：（推荐）

![image-20201207200043340](C:\Users\localuser\AppData\Roaming\Typora\typora-user-images\image-20201207200043340.png)



实现：

![image-20201207200244179](C:\Users\localuser\AppData\Roaming\Typora\typora-user-images\image-20201207200244179.png)

```java
/**
 * 使用自己写的 MyUncaughtExceptionHandler
 *
 */
public class UseOwnUncaughtExceptionHandler implements Runnable{

    public static void main(String[] args) throws InterruptedException {

        // 设置全局的 UncaughtExceptionHandler 用于捕获异常
        Thread.setDefaultUncaughtExceptionHandler(new MyUncaughtExceptionHandler("捕获器1"));

        new Thread(new UseOwnUncaughtExceptionHandler(), "Mythread-1").start();
        Thread.sleep(300);
        new Thread(new UseOwnUncaughtExceptionHandler(), "Mythread-2").start();
        Thread.sleep(300);
        new Thread(new UseOwnUncaughtExceptionHandler(), "Mythread-3").start();
        Thread.sleep(300);
        new Thread(new UseOwnUncaughtExceptionHandler(), "Mythread-4").start();
    }
    
    @Override
    public void run() {
        throw new RuntimeException();
    }
}
```

![image-20201207203321429](C:\Users\localuser\AppData\Roaming\Typora\typora-user-images\image-20201207203321429.png)

























































































































































